version: '3.8'

services:
  albion-build-generator:
    build: .
    container_name: albion-build-generator
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.albion.rule=Host(`albion.localhost`)"
      - "traefik.http.services.albion.loadbalancer.server.port=80"

networks:
  default:
    name: albion-network